import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forget Password",
  description: "Generated by create next app",
};

export default function Forgot() {
  return (
    <div>Forgot</div>
  )
}
