import React from 'react'
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};

export default function Regiter() {
  return (
    <div>Regiter</div>
  )
}
